apiVersion: apps/v1
kind: Deployment
metadata:
  name:  agile-test
  namespace: demo
spec:
  selector:
    matchLabels:
      app: agile-test
  template:
    metadata:
      labels:
        app: agile-test
    spec:
      containers:
        - name: agile-test
          image: mirajehossain/agile-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
